### PR TITLE
Implemented query_expansion function in search for free_text_query

### PR DESCRIPTION
**Pull request by SalsabilTasnia**

### CODE REVIEW

**Comment by SalsabilTasnia** [comment]
Do take a look at the pr. I observed that after implementing query_expansion, the number of Doc IDs in output file is a lott more

**Comment by hcwong** [comment]
> Do take a look at the pr. I observed that after implementing query_expansion, the number of Doc IDs in output file is a lott more

Perhaps you might want to set a limit? Or only get the synonyms of query terms with high weightage.

**Comment by SalsabilTasnia** [comment]
> > Do take a look at the pr. I observed that after implementing query_expansion, the number of Doc IDs in output file is a lott more
> 
> Perhaps you might want to set a limit? Or only get the synonyms of query terms with high weightage.

Sure, should I be setting a threshold for high value of query term weightage? Or should I expand the synonyms for the word with the highest weightage within a query?

**Comment by hcwong** [comment]
> > > Do take a look at the pr. I observed that after implementing query_expansion, the number of Doc IDs in output file is a lott more
> > 
> > 
> > Perhaps you might want to set a limit? Or only get the synonyms of query terms with high weightage.
> 
> Sure, should I be setting a threshold for high value of query term weightage? Or should I expand the synonyms for the word with the highest weightage within a query?
> 
> I think either is fine. You can try uploading to the leaderboard and see if performance drops. If it drops then we can just leave the commented code and justidfy why we didnt merge query expansion in the end. (Cos as long as we tried to implement something we can get the bonus 20%)

I think either is fine. You can try uploading to the leaderboard and see if performance drops. If it drops then we can just leave the commented code and justidfy why we didnt merge query expansion in the end. (Cos as long as we tried to implement something we can get the bonus 20%)

**Comment by SalsabilTasnia** [comment]
> > > > Do take a look at the pr. I observed that after implementing query_expansion, the number of Doc IDs in output file is a lott more
> > > 
> > > 
> > > Perhaps you might want to set a limit? Or only get the synonyms of query terms with high weightage.
> > 
> > 
> > Sure, should I be setting a threshold for high value of query term weightage? Or should I expand the synonyms for the word with the highest weightage within a query?
> > I think either is fine. You can try uploading to the leaderboard and see if performance drops. If it drops then we can just leave the commented code and justidfy why we didnt merge query expansion in the end. (Cos as long as we tried to implement something we can get the bonus 20%)
> 
> I think either is fine. You can try uploading to the leaderboard and see if performance drops. If it drops then we can just leave the commented code and justidfy why we didnt merge query expansion in the end. (Cos as long as we tried to implement something we can get the bonus 20%)

Sure will do that

**Review by hcwong — APPROVED** [review]
looks good

**Comment by SalsabilTasnia** [comment]
> looks good

Do you mind checking it through one more time? I added some small changes just now

**Comment by hcwong** [comment]
> > looks good
> 
> Do you mind checking it through one more time? I added some small changes just now

thx, still looks alright

**Comment by SalsabilTasnia** [comment]
> > > looks good
> > 
> > 
> > Do you mind checking it through one more time? I added some small changes just now
> 
> thx, still looks alright
Thanks!! Is it ok to merge?

**Pull request merged**
